
- hosts: localhost
  connection: local

  vars:
    nodes:
      - k8s-master0
      - k8s-worker0
      - k8s-worker1

  tasks:
    - name: Delete existing nodes
      lxd_container:
        name: "{{ item }}"
        state: absent
      with_items: "{{ nodes }}"
      register: deleting

    - debug:
        var: deleting
        verbosity: 2

    - name: Create all the nodes
      lxd_container:
        name: "{{ item }}"
        state: started
        config:
          limits.cpu: "2"
          limits.memory: 1GB
          limits.memory.swap: "false"
          linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
          raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw sys:rw"
          security.nesting: "true"
          security.privileged: "true"
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/bionic/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      with_items: "{{ nodes }}"

    # - name: Stop existing nodes
    #   lxd_container:
    #     name: "{{ item }}"
    #     state: stopped
    #   with_items: "{{ nodes }}"
    #   register: stopping
    #
    # - debug:
    #     var: stopping
    #     verbosity: 2
    #
