
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/bionic/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      with_items:
        - k8s-master0
        - k8s-worker0
        - k8s-worker1
