
- hosts: localhost
  connection: local

  vars:
    nodes:
      - k8s-master0
      - k8s-worker0
      - k8s-worker1

  tasks:
    - name: Delete existing nodes
      lxd_container:
        name: "{{ item }}"
        state: absent
      with_items: "{{ nodes }}"
      register: deleting

    - debug:
        var: deleting

    - name: Create all the nodes
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/bionic/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      with_items: "{{ nodes }}"
